feat: Support for additional template variables
pawamoy/git-changelog pull request #73
Opened 2024-03-17 07:32 UTC by chme

When using a custom Jinja template to render the changelog, it would be great, if additional context information could be accessed in that template. This feature request should be related to #17.

With the changes in this PR, additional context can be passed as key/value pairs either via CLI or via the toml config file.

To pass variables via CLI, the option `--template-var KEY VALUE` can be given multiple times.

To define variables in a configuration file, the variables can be defined in a "[template_vars]"  table.

``` toml
[template_vars]
KEY = "VALUE"
```

When template vars are given via CLI and via config file, they are merged with the CLI vars taking precedence.

All values are accessible in the template through the "template_vars" (dict) variable.

The parsing of the CLI option into a dict is based on this gist: https://gist.github.com/vadimkantorov/37518ff88808af840884355c845049ea

(Unfortunately argparse does not support it out of the box, or at least I could not find a better way to achieve this)

2024-03-17 18:01 UTC, pawamoy requested changes
Amazing feature once again! Thank you so much :blush: 

This all looks good, but I think I would prefer the following syntax on the CLI: `--template-var key=value`. We can do `key_value.split("=", 1)` so that values can have the `=` character too. What do you think?

Also, I don't think I like "template var" for the name and variable/parameter names in the code. What do you think of "jinja context" instead? This way we can also add a short option with `-j` which is not yet taken :slightly_smiling_face: I would then pass this context as `context` or `user_context` when rendering the template ("jinja" would be a bit redundant there).

Finally, it will need some documentation too! I can help with that if needed.

2024-03-17 18:01 UTC, pawamoy commented on src/git_changelog/cli.py
> +            setattr(namespace, self.dest, {})
I suppose this is necessary because we don't pass any default value in the call to `parser.add_argument`?

2024-03-17 18:01 UTC, pawamoy commented on src/git_changelog/cli.py
> +    print(opts)
Should be removed.

2024-03-17 18:01 UTC, pawamoy commented on src/git_changelog/cli.py
> +    # Merge template_vars
```suggestion
    # Merge template variables.
```

2024-03-17 18:01 UTC, pawamoy commented on src/git_changelog/cli.py
> +    template_vars: str | None = None,
I think it should be `dict[str, Any] | None`?
Also it needs a description in the docstring.

2024-03-17 18:01 UTC, pawamoy commented on src/git_changelog/cli.py
> +        )
```suggestion
        rendered = jinja_template.render(
            changelog=changelog,
            template_vars=template_vars,
            in_place=True,
        ).rstrip("\n") + "\n"
```

(if Ruff doesn't complain)

2024-03-17 18:01 UTC, pawamoy commented on tests/test_cli.py
> +        """.lstrip(),
`lstrip` does nothing here, since the string starts with `[`. You probably meant to use something like `textwrap.dedent`, to dedent every line?

2024-03-17 18:01 UTC, pawamoy commented on tests/test_cli.py
> +        fh.write("{% for key, val in template_vars.items() %}{{ key }} = {{ val }}\n{% endfor %}")
```suggestion
    template.write_text("{% for key, val in template_vars.items() %}{{ key }} = {{ val }}\n{% endfor %}")
```

2024-03-17 18:01 UTC, pawamoy commented on tests/test_cli.py
> +    assert contents == "k1 = v1\nk2 = v2\nk3 = v3\n"
```suggestion
    contents = repo.path.joinpath("CHANGELOG.md").read_text()
    assert contents == "k1 = v1\nk2 = v2\nk3 = v3\n"
```

2024-03-18 19:34 UTC, chme commented
> This all looks good, but I think I would prefer the following syntax on the CLI: `--template-var key=value`. We can do `key_value.split("=", 1)` so that values can have the `=` character too. What do you think?

I first thought, that having key and value as separate parameters, would make it a bit easier, when calling it from a shell script (if the value has to be escaped).
But searching a bit, using the `=` between key and value seems more common (though its difficult to find good examples).

I am fine with `--template-var key=value`.

> Also, I don't think I like "template var" for the name and variable/parameter names in the code. What do you think of "jinja context" instead? This way we can also add a short option with `-j` which is not yet taken 🙂 I would then pass this context as `context` or `user_context` when rendering the template ("jinja" would be a bit redundant there).

Naming is not something I am especially good at :grin:, so whatever you prefer is fine for me.
That said, "template variable" is the term used in the [jinja documentation](https://jinja.palletsprojects.com/en/3.0.x/templates/#variables). 

> Finally, it will need some documentation too! I can help with that if needed.

I can add some documentation (though help on that would be appreciated).

2024-03-19 15:41 UTC, pawamoy commented
I've pushed some docs :smile: Feel free to tweak them.

2024-03-21 05:56 UTC, chme commented on src/git_changelog/cli.py
> +            setattr(namespace, self.dest, {})
Defining a default empty dict is not enough. The problem is, when determining whether an argument was explicitly passed via CLI or not:

``` python
    # Determine which arguments were explicitly set with the CLI
    sentinel = object()
    sentinel_ns = argparse.Namespace(**{key: sentinel for key in opts})
    explicit_opts_dict = {
        key: opts.get(key, None)
        for key, value in vars(parser.parse_args(namespace=sentinel_ns, args=args)).items()
        if value is not sentinel
    }
```

During the `parser.parse_args(...)` call, the `_ParseDictAction` is called with the attribute  being an object "special variables". I don't fully understand how this works. Let me know if you know of a better way to handle this.

2024-03-21 10:46 UTC, pawamoy commented on src/git_changelog/cli.py
> +            setattr(namespace, self.dest, {})
Right, I see! That's good then :)

2024-03-21 13:11 UTC, pawamoy commented on src/git_changelog/cli.py
> +    jinja_context: dict[str, str] | None = None,
It's true that values passed from the CLI will always be strings, but when using the API directly from Python, values could be anything, so I think it should be `dict[str, Any]`.

2024-03-21 13:13 UTC, pawamoy commented on tests/test_cli.py
> +    assert contents == "k1 = v1\nk2 = v2\nk3 = v3\n"
```suggestion
```

2024-03-23 05:08 UTC, chme commented
> I've pushed some docs 😄 Feel free to tweak them.

Awesome, thanks! I only, did a small change in the config file example.

I changed it now to use KEY=VALUE and I hope, I addressed all other comments as well.

2024-03-23 11:30 UTC, pawamoy commented on src/git_changelog/cli.py
> +        settings["jinja_context"] = jinja_context
IIUC, `settings["jinja_context"]` is always a dict, so we can safely update it directly.

```suggestion
    settings["jinja_context"].update(jinja_context)
```

2024-03-23 11:31 UTC, pawamoy approved these changes
LGTM, thanks a lot :slightly_smiling_face:

2024-03-23 11:34 UTC, merged